export const ACTOR_LIST_REQUEST = 'ACTOR_LIST_REQUEST';
export const ACTOR_LIST_SUCCESS = 'ACTOR_LIST_SUCCESS';
export const ACTOR_LIST_FAIL = 'ACTOR_LIST_FAIL';

export const MORE_ACTOR_LIST_REQUEST = 'MORE_ACTOR_LIST_REQUEST';
export const MORE_ACTOR_LIST_SUCCESS = 'MORE_ACTOR_LIST_SUCCESS';
export const MORE_ACTOR_LIST_FAIL = 'MORE_ACTOR_LIST_FAIL';