export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST';
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS';
export const MOVIE_LIST_FAIL = 'MOVIE_LIST_FAIL';

export const MORE_MOVIE_LIST_REQUEST = 'MORE_MOVIE_LIST_REQUEST';
export const MORE_MOVIE_LIST_SUCCESS = 'MORE_MOVIE_LIST_SUCCESS';
export const MORE_MOVIE_LIST_FAIL = 'MORE_MOVIE_LIST_FAIL';
