export const SHOW_LIST_REQUEST = 'SHOW_LIST_REQUEST';
export const SHOW_LIST_SUCCESS = 'SHOW_LIST_SUCCESS';
export const SHOW_LIST_FAIL = 'SHOW_LIST_FAIL';

export const MORE_SHOW_LIST_REQUEST = 'MORE_SHOW_LIST_REQUEST';
export const MORE_SHOW_LIST_SUCCESS = 'MORE_SHOW_LIST_SUCCESS';
export const MORE_SHOW_LIST_FAIL = 'MORE_SHOW_LIST_FAIL';